"""Initial migration

Revision ID: ea63dc4f4880
Revises: 
Create Date: 2024-11-10 21:15:04.112180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea63dc4f4880'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asrun_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('date_processed', sa.DateTime(), nullable=True),
    sa.Column('broadcast_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_title', sa.String(), nullable=True),
    sa.Column('event_category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('spot_type', sa.String(), nullable=True),
    sa.Column('spot_type_category', sa.Enum('COMMERCIAL', 'PROGRAM', 'STATION_ID', 'PSA', 'ID', 'FL', 'NS', 'GS', 'SF', 'PG', 'RS', 'FI', 'PR', 'PS', 'PA', 'FR', 'DA', 'TN', 'AJ', 'UNKNOWN', name='spottype'), nullable=True),
    sa.Column('start_mode', sa.String(), nullable=True),
    sa.Column('start_mode_category', sa.Enum('FIXED', 'FOLLOW', 'SEQUENTIAL', 'MANUAL', 'UNKNOWN', name='startmode'), nullable=True),
    sa.Column('end_mode', sa.String(), nullable=True),
    sa.Column('end_mode_category', sa.Enum('DURATION', 'FIXED', 'MANUAL', 'FOLLOW', 'UNKNOWN', name='endmode'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('house_number', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('segment_number', sa.String(), nullable=True),
    sa.Column('segment_name', sa.String(), nullable=True),
    sa.Column('program_name', sa.String(), nullable=True),
    sa.Column('asrun_file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asrun_file_id'], ['asrun_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('asrun_files')
    # ### end Alembic commands ###
